#!/bin/sh
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Start by installing the command line tools i.e. GCC
xcode-select --install

# Install zsh
source install/zsh.sh

# Remove autogenerated zshrc
rm ~/.zshrc

source install/homebrew.sh
source install/ruby.sh
source install/gpg.sh
source install/python.sh
source install/java.sh
source install/docker.sh
source install/osx.sh

stow config
source install/nvim.sh

stow zsh
stow git
stow ruby
stow ssh

dark-mode on

osascript -e "set Volume 7"

tput bel && sleep 0.33s && tput bel && sleep 0.33s && tput bel && sleep 0.33s && tput bel && sleep 0.33s && tput bel && sleep 0.33s && tput bel && sleep 0.33s && tput bel && sleep 0.33s && tput bel && sleep 0.33s && tput bel && sleep 0.33s && tput bel && sleep 0.33s
say "Finished installing. Please reboot!"
